### ISSUE TITLE
Portfolio: application deploy

### ISSUE THREAD

**Issue by Graciano1997** [Graciano1997/portofolio-graciano#8]
I should like to share my portfolio's link to the online version of my app.

[Portofolio-Graciano](https://graciano1997.github.io/portofolio-graciano/)

**Comment by AlphaNtihinduka** [comment]
# STATUS: APPROVED :green_circle: :clap: 
## Hi @Graciano1997  🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Proper use of github pages ✔️ 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

**Comment by Graciano1997** [comment]
I come to thank you for your recognition 💯 💯  🙏 🙏  🍾 🍾 🍰 🍰
